name: My Worlds
main: com.bergerkiller.bukkit.mw.MyWorlds
version: 1.46
author: bergerkiller
softdepend: [Spout]
depend: [BKCommonLib]
dev-url: http://dev.bukkit.org/server-mods/my-worlds/
commands:
    world:
        description: Cross-world commands to manage your worlds
        aliases: [myworlds, mw, worlds]
        usage: |
            /world ? for usage
    tpp:
        description: Cross-world teleportation commands
        usage: /tpp [Portalname/Worldname] - Teleport to a Portal or World